### ISSUE TITLE
opam fails during "make depend"

### ISSUE THREAD

**Issue by dvn0** [roburio/unipi#1]
Hello,

This is a nice project, and I have some limited experience building MirageOS unikernels. I'm experiencing a problem while trying to install the dependencies:

First I run:

`mirage configure -t unix`

and then:

`make depend`

and I get this output:

```
  1 opam pin add -k path --no-action --yes mirage-unikernel-unipi-unix . && opam depext --yes --update mirage-unikernel-unipi-unix ; opam pin remove --no-action mirage-unikernel-unipi-unix
  2 Package mirage-unikernel-unipi-unix does not exist, create as a NEW package? [Y/n] y
  3 [mirage-unikernel-unipi-unix.~dev] synchronised from file:///home/[user]/src/unikernels/mirageos/unipi
  4 mirage-unikernel-unipi-unix is now pinned to file:///home/[user]/src/unikernels/mirageos/unipi (version ~dev)
  5 # Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
  6 [ERROR] No solution for mirage-unikernel-unipi-unix: Sorry, no solution found: there seems to be a problem with your request.
  7                                                                                 
  8                                                                                 
  9 Command failed: opam list --readonly --external  '--resolve=mirage-unikernel-unipi-unix' returned 20
 10 Ok, mirage-unikernel-unipi-unix is no longer pinned to file:///home/[user]/src/unikernels/mirageos/unipi (version ~dev)
 11 opam install -y --deps-only .                                                   
 12 Sorry, no solution found: there seems to be a problem with your request.        
 13                                                                                 
 14 No solution found, exiting                                                      
 15 make: *** [Makefile:15: depend] Error 20   
```

**Comment by dvn0** [comment]
I've also tried with `hvt`, and `virtio` targets, and the result is the same.

**Comment by hannesm** [comment]
Hi @dvn0, what is your OCaml version (`ocaml --version`)? What is your mirage version (`mirage --version`)?

**Comment by dvn0** [comment]
My relevant software versions:

```
The OCaml toplevel, version 4.09.0
opam 2.0.5
mirage v3.9.0
```

**Comment by hannesm** [comment]
since you're on debian, maybe you're running into this issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908203 -- is your opam package a 2.0.5-1?

**Comment by hannesm** [comment]
hmm no, due to the conduit 3 release there are some issues in respect to version constraints. I'll try to figure them out and find a solution.

**Comment by dvn0** [comment]
> since you're on debian, maybe you're running into this issue https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908203 -- is your opam package a 2.0.5-1?

oh, interesting. I am on Ubuntu actually, and yes my package is the 2.0.5-1... :/

**Comment by hannesm** [comment]
but 2.0.5-1 is the good one AFAICT :)

**Comment by hannesm** [comment]
sorry for the inconvenience and late reply, I finally worked on this issue and 70092ef has a solution (which compilcates the build process slightly). if you still have trouble, please reopen this issue with an updated error message. Thanks.
