### ISSUE TITLE
Querying the website through the IP address directly leads to an unreachable page

### ISSUE THREAD

**Issue by kit-ty-kate** [roburio/unipi#15]
I think it would be nice to redirect to `Key_gen.hostname ()` when possible to avoid having this problem.
It's not a big problem but it'd be nice to clean up the log output a little (some bots seem to use the IP address directly or something) as it shows there as an error or an internal exception in some cases.

**Comment by hannesm** [comment]
If I understand the code correctly, the `redirect` function (that is used for http -> https redirecting) will (a) look at `Key_gen.hostname ()` and, if provided, redirect there. (b) look into the `host` header of the request, and redirect to `http://<host>`

Only if neither is present, a bad request is issued. Which scenario are you looking at?

**Comment by kit-ty-kate** [comment]
Sorry if i wasn't clear. By "unreachable page" i meant the `Warning: Potential Security Risk Ahead` page from firefox warning us that the page we're looking at does not match the SSL certificate.

For example this is what i get when trying to reach the robur.coop website using its IP address directly:
![scrn-2022-11-10-15-24-20](https://user-images.githubusercontent.com/2611789/201135880-9fe124ca-67bf-40e9-864f-2e4c1f54ab09.png)

**Comment by kit-ty-kate** [comment]
Ah i see. It does explain the original issue, sorry for the waste of time.
