### ISSUE TITLE
Unipi sets content-type on / to application/octet-stream

### ISSUE THREAD

**Issue by reynir** [roburio/unipi#16]
At least for the build I did about two days ago.

**Comment by hannesm** [comment]
Yes, that's the default mime type by default. Should we change that? There's the `--default-mime-type` command line parameter (which default is `application/octet-stream`).

**Comment by reynir** [comment]
I think we should use `path ^ "/index.html"` for resolving the mime type when we use that path for the content. #17 does that.

**Comment by hannesm** [comment]
Sure, if that is all needed, that is good. For our robur.coop deployment I set the default mime type to text/html via command-line since all the resources do not use file extensions.

I also thought that we could support .gitattributes and put the mime-types in there ;)
