### ISSUE TITLE
Something adds an extra slash in http path

### ISSUE THREAD

**Issue by reynir** [roburio/unipi#8]
I found that unipi wasn't able to clone a repository. After some debugging I discovered *something* added an extra slash in the beginning of the path so instead of requesting https://git.data.coop/halfd/new-website it was requesting https://git.data.coop//halfd/new-website. Unfortunately for me gitea does not like that and returns a 404 unlike Github (see https://github.com/go-gitea/gitea/issues/20462 for the gitea issue).

I realize the fault likely lies somewhere else, maybe in ocaml-git. I'm creating the issue here as I am not able to find the cause right now.

The build is done here using docker and an opam file generated with mirage3 configure: https://git.data.coop/reynir/docker-unipi

**Comment by hannesm** [comment]
closing, this is an issue in the ocaml-git implementation, with the upstream PR https://github.com/mirage/ocaml-git/pull/580
